### PR TITLE
(RFC) My changes

### PR DESCRIPTION
**Pull request by MaddTheSane**
These are all the changes that I have done over the years to Colloquy. If you want, you can pick and choose which ones you want to use.

* Migrate most icons and images to Xcode assets.
* Use Objective-C subscript getters and setters for `NSArray`s and `NSDictionary`s.
* Nullability and generics metadata.
* Objective-C class properties.
* Have ChatCore build a module map.
* Objective-C 2.0 getters and setters.
* Declare Colloquy plug-in calls as Obj-C properties instead of informal protocols.
* Use `instancetype` where appropriate.
* Additional Swift metadata (Swift hates exceptions).
* Use `OSType` for four-char codes.
* Use Obj-C literals where possible.
* Convert most of the plug-ins to ARC.

### CODE REVIEW

**Comment by zadr** [comment]
@MaddTheSane There's some things in here that would be great to have, for example, the Chat Core module map sounds useful!

That said, I'm confused by this pull request. There's a whole lot of code that seems to have somehow become attributed to you (due to merging?) rather than the original author. Merging it in would make following history super difficult. This misattribution also means there's a lot of existing code that needs re-reviewing, rather than only new bits.

While we're open to accepting the changes (again, they do sound good!), I don't think this PR is one that we can accept; I don't have time to look through 250 commits to find out what's new, what's code that we already wrote, and to review the new bits more closely (and without wanting to put words into @akempgen's mouth, I don't believe he does either).

**Comment by MaddTheSane** [comment]
It was more a case of saying "This is what I have" than a case of a serious merge.

That said, I can do some splitting up of the major changes that I have done, such as the nullability and generics metadata.

**Comment by akempgen** [comment]
I agree with @zadr, although I‘m not sure why we would need the module map. 😀 Why don‘t you join us in our chat room some time? I think that would make discussing these things easier. Then you would already know beforehand, what kind of changes we want to see in the project, and not only after you did the work and created the pull requests.

**Comment by MaddTheSane** [comment]
Having a module map helps immensely with Swift code.

**Pull request closed without merging**
