### PR TITLE
Poke the nibs.

### PR DESCRIPTION
**Pull request by MaddTheSane**
Also fix some unavailable images used in nibs.
Have the buttons that use NSAdd/RemoveTemplate be bordered, to match the old behavior.

### CODE REVIEW

**Comment by zadr** [comment]
Thanks for sending this PR in!

This is a pretty large pull request, and due to the way nibs work(ed back in the day), kind of hard to verify that things still work as expected afterwards— for example, poking the nibs (opening them in a new version of Xcode?) seems to have resulted in a lot of autoresizing masks being moved around from one view and to another (parent?) view.

We'll try and look it over, but, we can't promise that it'll be approved in a reasonable timeframe, or that changes won't be overridden by other things in the meantime and need some rebasing.

**Comment by MaddTheSane** [comment]
I mostly did open the nibs in Xcode 9, changed the deployment target of the nibs to match the project's, and set the Xcode version that can open them to the latest. I also did change some of the buttons that used to be just images that looked like buttons (such as `addWidgetSelected`) from unbordered buttons into bordered and using a comparable template image (`NSAddTemplate`). This matches the old looks of the buttons and makes them scalable on Retina displays.

After saving them with a newer version of Xcode, the nib package contains a `designable.nib` and a `keyedobject.nib`. Moving the `designable.nib` to outside the package and renaming it to `something.xib` creates a xib file editable by Xcode. Having them be xibs is far more diff-friendly than the old nibs.

**Comment by zadr** [comment]
Would it be possible for a new PR to be sent in that changes buttons to be bordered, and not touching any other nib? Maybe a second commit with that fixes the unused images?

A PR that touches _all_ the nib's winds up being little too big for us to be able to examine or comfortably accept, sorry! :(

**Comment by MaddTheSane** [comment]
I'll see what I can do.

**Pull request closed without merging**
